apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-deployment
  labels:
    app: pvc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pvc-app
  template:
    metadata:
      labels:
        app: pvc-app
    spec:
      containers:
     - name: myvolumes-container
       image: tomcat:8.5
       volumeMounts:
        - name: pv
          mountPath: "/usr/local/tomcat/logs"
    volumes:
     - name: pv
       persistentVolumeClaim:
         claimName: my-pvc      
