apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test
  labels:
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
      author: bobby
  template:
    metadata:
      labels:
        tier: frontend
        author: bobby
    spec:
      containers:
      - name: lb
        image: lerndevops/samplepyapp:v1
